### ISSUE TITLE
How should we inject config file to a Sensu plugin?

### ISSUE THREAD

**Issue by tanin47** [sensu-plugins/sensu-plugin#108]
I have encountered this exception:

```
/usr/local/lib/ruby/gems/2.1/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:80:in `api_request': api.json settings not found. (RuntimeError)
    from /usr/local/lib/ruby/gems/2.1/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:123:in `stash_exists?'
    from /usr/local/lib/ruby/gems/2.1/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:135:in `block (2 levels) in filter_silenced'
    from /usr/local/lib/ruby/2.1/timeout.rb:90:in `block in timeout'
    from /usr/local/lib/ruby/2.1/timeout.rb:33:in `block in catch'
    from /usr/local/lib/ruby/2.1/timeout.rb:33:in `catch'
    from /usr/local/lib/ruby/2.1/timeout.rb:33:in `catch'
```

I have figured that it is because sensu-plugin doesn't read the configuration, and I've found this line: https://github.com/sensu-plugins/sensu-plugin/blob/master/lib/sensu-plugin/utils.rb#L5

I wonder what the best way is to inject the config files to sensu-plugin.

Please note that, if I manually run the handler with the correct env var, it works. Here's how I do it:

```
cat test2.json | SENSU_CONFIG_FILES=conf.d/api.json:conf.d/logstash.conf /usr/local/bin/handler-logstash.rb
```

Thanks!

**Comment by cwjohnston** [comment]
Hi @tanin47, I apologize that your issue has gone unanswered for so long. By default a plugin using this library should have access to the `@settings` instance variable, containing the local Sensu configuration loaded from disk. In your case, I believe you're falling afoul of one or two bugs that are addressed in today's 1.4.0 release of this library.

First, due to the issue described in https://github.com/sensu-plugins/sensu-plugin/pull/141 plugins which do not explicitly require 'json' may silently fail to load Sensu settings from disk.

Second, versions of sensu-plugin prior to 1.4.0 do not provide default values for `api` host and port configuration, so failing to load Sensu config can cause this error (with misleading reference to api.json) raised by `api_request` method.

I believe that updating any custom plugins to use version 1.4.0 of this library should resolve either or both of these cases. If you are still seeing a problem, please let us know.
