### ISSUE TITLE
need a way to disable refresh

### ISSUE THREAD

**Issue by joshzitting** [sensu-plugins/sensu-plugin#186]
We would like a way to disable refresh on our alarms all together... Is there already a way to do this? 
Thanks

**Comment by cwjohnston** [comment]
Hi @joshzitting, occurrence filtering, the logic which makes use of `occurrences` and `refresh` attributes, has moved into the [occurrences filter extension](https://github.com/sensu-extensions/sensu-extensions-occurrences/) and version 2.0 of this library disables occurrence filtering in plugins themselves. You can read more about this (here on our blog)[https://blog.sensuapp.org/deprecating-event-filtering-in-sensu-plugin-b60c7c500be3].

All that said, actually using these changes requires that the handler plugins you're relying on be upgraded to depend on `sensu-plugin ~> 2.0` so that filtering inside the handler itself is disabled by default. Then it becomes optional to apply the `occurrences` filter to individual handlers as you see fit.

I hope this information is helpful to you. If you have any additional questions or concerns, please join [our Community Slack team](https://slack.sensu.io) where we and others in the Sensu community are better able to help you with plugin versioning and configuration changes.
