### ISSUE TITLE
Ability to read from settings in plugin check

### ISSUE THREAD

**Issue by parisholley** [sensu-plugins/sensu-plugin#85]
Notice that commands are logged with parameters sent to the check.rb file from a plugin. This could be problematic as the parameters can container user/pass combos. Wouldn't a better approach be to load global settings first, then allow override from CLI?

**Comment by cwjohnston** [comment]
Hi @parisholley, I apologize that your issue has gone unanswered for so long. 
I agree that it makes more sense for plugins to load "secret" configuration values from Sensu config rather than using command line flags, but this is left up to individual plugin authors to implement.

By default a plugin using this library should have access to the `@settings` instance variable, containing the local Sensu configuration loaded from disk. If you haven't been able to use `@settings` to access Sensu config from disk, that may be because of bugs fixed in version 1.4.0 of this library, e.g. #141.
